### ISSUE TITLE
Fails to run, gives errors in console

### ISSUE THREAD

**Issue by nkshio** [voiceittech/VoiceItApi2WebSDK#4]
Follow the steps in `readme` to run the demo app using a Nodejs server. 
I wasn't able to do any of the available enrollments. 

<img width="1440" alt="Screenshot 2019-07-09 at 12 54 31 AM" src="https://user-images.githubusercontent.com/10398420/60837400-b4897200-a1e5-11e9-8d2a-3bfd168bbada.png">

Running locally, Tested browsers: Chrome, Safari

Looking out for a quick hotfix, or helpful insights.

**Comment by gilgameshskytrooper** [comment]
Let's talk on Slack
